# Generated by Django 6.0.6 on 2026-06-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('county', models.CharField(max_length=100)),
                ('membership_type', models.CharField(choices=[('Junior', 'Junior Membership'), ('Senior', 'Senior Membership'), ('Social', 'Social Membership'), ('Supporter', 'Supporter Membership')], max_length=20)),
                ('athletic_discipline', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('medical_information', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
