# Generated by Django 6.0.6 on 2026-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='athletes/')),
                ('category', models.CharField(max_length=100)),
                ('achievements', models.TextField()),
            ],
        ),
    ]
